name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run unit tests
        run: python -m unittest discover -s app/tests -v

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -recursive terraform

      - name: Terraform init
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Build Docker image
        run: docker build -t 8byte-app:${{ github.sha }} ./app
